basic.showIcon(IconNames.Happy)
basic.pause(2000)
maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
music.playTone(523, music.beat(BeatFraction.Whole))
basic.pause(500)
maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
music.playTone(659, music.beat(BeatFraction.Whole))
basic.pause(500)
music.playTone(784, music.beat(BeatFraction.Whole))
maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
basic.pause(500)
music.playTone(831, music.beat(BeatFraction.Quarter))
maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOff)
basic.pause(250)
music.playTone(831, music.beat(BeatFraction.Quarter))
maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
basic.pause(250)
music.playTone(831, music.beat(BeatFraction.Quarter))
maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
basic.pause(1000)
for (let index = 0; index < 23; index++) {
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)
    basic.pause(1000)
    maqueen.motorStop(maqueen.Motors.All)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 32)
    basic.pause(300)
    maqueen.motorStop(maqueen.Motors.M2)
}
basic.showIcon(IconNames.Asleep)
music.playTone(262, music.beat(BeatFraction.Whole))
basic.pause(500)
music.playTone(196, music.beat(BeatFraction.Whole))
basic.forever(function () {
	
})
